name: Create VPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Create VPS (example)
      run: |
        echo "Tạo VPS ở đây"
        # ví dụ chạy script shell tạo vps
        # ./scripts/create-vps.sh
